pullRequestOpened: >
  Thank you for your contribution to easyInterface.
  
  Please ensure:

  - [ ] You include a description of the pull request

  - [ ] Your code builds clean without any errors or warnings

  - [ ] You are using approved terminology

  - [ ] You have added unit tests
